### PR TITLE
FISH-8 Metric Selection Wizard

### PR DESCRIPTION
**Pull request by jbee**
### Summary
This PR adds a advance search and selection dialog to monitoring console that replaces previous means of selecting metric series.

The wizard is used when
* adding a new widget to the page using the _Page_ settings _Add Widgets_
* changing a widgets _Series_ property in the _Data_ settings
* adding a new widget to the page using the new `+` button placed on empty cells in the grid

The wizard has multiple search filters. Depending on the _Source_ selected further filters become available.
Especially _MicroProfile Metrics_ do support a variety of filters that work on the metadata properties of MP Metrics.

screenshot-x1_8080-2020 07 17-11_09_25

Selected filters are directly applied. Selections may cause some filters to disappear that no longer work in combination with the new selection. For example when selecting _Server Metrics_ as _Source_ none of the MicroProfile specific filters are shown or effective.

Text filters with input immediately filter the matches using _contains_ logic on the filtered property.

Not all matches have the same metadata available. Therefore MicroProfile metrics have name and descriptions while other metrics don't have such extra information.

Once entries are selected in the list of matches they are added to the selection shown right. 
They can be deselected both in the list of matches and the list of selections.

If the dialog is closed using _OK_ with no selection made this has the effect of _Cancel_.

### Testing
Manual testing.

Ideally install Payara with https://github.com/payara/Payara/pull/4796 (build affected module and copy to `glassfish/modules` is enough).
Manually deploy the updated webapp and open monitoring console.

Wizard is accessed via:
screenshot-x1_8080-2020 07 17-11_20_50
screenshot-x1_8080-2020 07 17-11_20_07
screenshot-x1_8080-2020 07 17-11_19_15

This will show the selection dialog
screenshot-x1_8080-2020 07 17-11_21_15

### Documentation
https://github.com/payara/Payara-Community-Documentation/pull/48

### CODE REVIEW

**Review by Pandrex247 — APPROVED** [review]
I think the only "bug" I found was that if you open the widget and then go back to the previous page (e.g. right click outside widget and hit back) the widget doesn't disappear and any changes you make (or new widget you intended to add) are not saved to the old or new page.
Not sure if that counts as a bug though, and it's pretty niche!

Aside from that the matching of MicroProfile Name is a bit finicky. For example, to match _LoadedClassesCount_, searching for _Loaded_ matches, but searching for _Currently_ doesn't.

Tested by building Payara Server on the _FISH-8_ branch with monitoring console webapp property set to 1.3-SNAPSHOT.

**Comment by jbee** [comment]
> Aside from that the matching of MicroProfile Name is a bit finicky. For example, to match LoadedClassesCount, searching for Loaded matches, but searching for Currently doesn't.

Can you expand on this? Currently isn't in the name so why would you expect a match?

**Comment by Pandrex247** [comment]
> 
> 
> > Aside from that the matching of MicroProfile Name is a bit finicky. For example, to match LoadedClassesCount, searching for Loaded matches, but searching for Currently doesn't.
> 
> Can you expand on this? Currently isn't in the name so why would you expect a match?

When you look at the entry displayed in the wizard, the "name" in bold for this metric is _Currently Loaded Classes_ (or something similar, going ottomh)

**Comment by jbee** [comment]
@Pandrex247 Now I got you, it might be that the way I search the string is flawed. Will check that when I am back.

**Comment by jbee** [comment]
@Pandrex247 added a _display name_ filter that filters on the property you were expecting to filter by when using _name_ filter.

**Review by Pandrex247 — APPROVED** [review]

**Pull request merged**
